name: Publish
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: python3 --version
      - run: pip install -r requirements.txt
      - run: pip install pyinstaller
      - run: pyinstaller --name aws-auto-inventory-${{ matrix.os }} --onefile scan.py

      - uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: aws-auto-inventory-${{ matrix.os }}
          path: dist\aws-auto-inventory-windows-latest.exe

      - uses: actions/upload-artifact@v3
        if: matrix.os != 'windows-latest'
        with:
          name: aws-auto-inventory-${{ matrix.os }}
          path: ./dist/aws-auto-inventory-${{ matrix.os }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          name: aws-auto-inventory-ubuntu-latest

      - uses: actions/download-artifact@v4.1.7
        with:
          name: aws-auto-inventory-macos-latest

      - uses: actions/download-artifact@v4.1.7
        with:
          name: aws-auto-inventory-windows-latest

      - run: mv aws-auto-inventory-ubuntu-latest aws-auto-inventory-ubuntu

      - run: mv aws-auto-inventory-macos-latest aws-auto-inventory-macos

      - run: mv aws-auto-inventory-windows-latest.exe aws-auto-inventory-windows.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          draft: true
          files: |
            aws-auto-inventory-ubuntu
            aws-auto-inventory-macos
            aws-auto-inventory-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
